### PR TITLE
Hurricane

### PR DESCRIPTION
**Pull request by EttnerAndreas**
Added hurricane dataset, see also #276.

### CODE REVIEW

**Comment by florianhartig** [comment]
Hi Andreas,

thanks for that. Some small suggestions:

* move example code to inst/examples (see other help files)
* I would not rename the data file, i.e. remove Data <- hurricanes
* Can you also switch LazyData: true in the DESCRIPTION?

**Comment by florianhartig** [comment]
About the unit tests: seems the git actions work at last. 

However, we definitely do not want to import the libraries for the data creation, can you maybe google what's the best practice for that? 

In the worst case, we could just move the data-raw outside the package, or maybe it should be ignored by the checks?

**Comment by EttnerAndreas** [comment]
> 
> 
>     * move example code to inst/examples (see other help files)
> 
>     * I would not rename the data file, i.e. remove Data <- hurricanes
> 
>     * Can you also switch LazyData: true in the DESCRIPTION?

I added in addition the example code to  inst/examples, but it is still in the help file created by roxygen. 
I did no longer rename the data file,
I removed LazyData, that means it is not automatically loaded with **_library(DHARMa)_**, users have to run **_data("hurricanes")_** first, see help file.


Elsewise, i did delete the data-raw folder, since some packages only provide the raw files [(see glmmTMB)](https://github.com/glmmTMB/glmmTMB/tree/master/glmmTMB) and this should work as well, might even be more elegant

**Comment by florianhartig** [comment]
Hi Andreas, 

OK, but if the help file is in inst/examples, you have to link to that, see other DHARMa functions.

About lazydata - I meant to set LazyData: true, it was switched off before (at least in master).

Checks stil fail, right?

**Comment by EttnerAndreas** [comment]
well, i think it is only one or two small changes, i will push one more change later tonight and hopefully it will pass than.
than i can fix the Description an I will compare again to other packages.

**Comment by EttnerAndreas** [comment]
I think, this should finally do it. 
Everything is working when loading library(DHARMa)

- The help file is working, 
- examples from inst/examples is linked with the help file
- Lazydata: True

**Comment by florianhartig** [comment]
Hi Andreas, 

where did the file for creating the data go now, I can't see it, is it still in the branch?

**Comment by florianhartig** [comment]
In EcoData, I have these files outside the package folder. Maybe you could investigate a bit what the best practice is and how other packages handle this.

**Comment by florianhartig** [comment]
make folder DHARMaData in https://github.com/florianhartig/DHARMa/tree/master/Code put creation scripts there

**Comment by florianhartig** [comment]
closes #277

**Pull request merged**
