### PR TITLE
Issue#190

### PR DESCRIPTION
**Pull request by EttnerAndreas**
Can you please have a look at this. I tried to to fix https://github.com/florianhartig/DHARMa/issues/190 with a TryCatch function.

I hope I included the code into the right file as well as I could not find an easy 'if-function' to solve this problem.

### CODE REVIEW

**Comment by florianhartig** [comment]
So, first of all, the branch has conflicts. You have to update from master and resolve the conflicts. 

Second, there seem to be a bunch of commits that have nothing to do with #190 , specifically changes the the github action stuff and other things?

**Comment by florianhartig** [comment]
Also, if I look at your changes, there's the weird thing that GH displays a change in every empty line as far as I can see ... is this a windows / mac issue (Ascii string for new line)? We should resolve this, else it's super annoying to review code changes.

**Comment by florianhartig** [comment]
OK, I think now I see what's the problem with this PR - you are doing this from your fork, which seems to have a bunch of changes, or is maybe not updated, which creates all these changes. Let's talk tomorrow shortly. I think it would be better to create a branch on my repo, and do the pull request from there!

**Comment by EttnerAndreas** [comment]
okay, I see. looks like the branch had some issue. I will simply fork DHARMa again, to get the updated version. and try it again, which should not be a big deal and otherwise, I would try the way of creating my own branches on the original DHARMa.

**Comment by florianhartig** [comment]
Witzig, schau dir mal https://github.com/florianhartig/DHARMa/commit/4da5af3fbf1f94f9ef59a8ca604decd49b636126 an - ist mir jetzt aufgefallen als ich im master einen check gemacht hatte, keine Ahnung warum das bei den Tests vorher nicht aufgetaucht ist, oder wir haben es übersehen

**Pull request closed without merging**
