### PR TITLE
Overdispersion

### PR DESCRIPTION
**Pull request by florianhartig**

### CODE REVIEW

**Comment by florianhartig** [comment]
@EttnerAndreas - can you have a look if you understand why this branch suddenly has a build error? This was created from the last update in master, but master checks out, and the branch previously also checked out!

**Comment by florianhartig** [comment]
p.s., Andreas, can you do a review of this? This mostly concerns the code in the functions that are used by users, which are not so major, it's mainly a slight change in the standard overdispersion function, and the introduction of this parametric version of the overdispersion function. I would like to merge this all asap and get 0.3.4 on the way

**Comment by EttnerAndreas** [comment]
good job
looks like it is fixed, I would be interested if you changed something specific

currently I am reviewing the new fucntions

**Comment by florianhartig** [comment]
No, I didn't fix anything. Maybe this was just a travis problem, I didn't look at the error message, sometimes one just gets build errors because the tests run too long, and that can happen because the servers are overloaded, if you trigger a re-build, the error is gone!

OK, thanks for the help function check. From my side, the branch could be merged!

**Comment by EttnerAndreas** [comment]
okay, think the text might disappeared.
alright, well I already merged it, do we need further tests? 
Interesting, I read a lot of those internet connection problems causing this error (56)

**Comment by florianhartig** [comment]
Hi Andreas, thanks, but if you do a review, please don't merge yet, I will always merge, just note what you think should be changed, or add improvements.

Absolutely nothing unclear about the help ;) ? I must be on fire then!

**Comment by EttnerAndreas** [comment]
It is quite clear, but nothing big
- for me, it would be interesting to get an easy answer on the benefits of 'refit = T' since it is computationally expensive

-The type changed from Pearson to PearsonChisq, Is there a way to implement both? might be useful to have further help with the application.
- maybe depending on the audience a further explanation of over/under- dispersion, when it is useful

**Comment by florianhartig** [comment]
OK, thanks, I've made an issue for that!

**Pull request merged**
